version: '3'

services:
  web:
    build: .
    container_name: bibliotheca_web
    command: sh -c "rm -f tmp/pids/server.pid && 
             bundle exec rails s -p 3000 -b '0.0.0.0'" 
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - app-storage:/app/storage
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:16.1-alpine
    container_name: bibliotheca_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "5432:5432"

volumes:
  app-storage: {}
  postgres_data: {}
  bundle: {}

networks:
  default: