version: '3'

services:
  web:
    build:
      context: .      
    container_name: rails
    command: sh -c "rm -f tmp/pids/server.pid &&
             bundle exec rails db:create db:migrate && 
             bundle exec rails server -p 3000"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - SECRECT_KEY_BASE=${SECRECT_KEY_BASE}
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
    volumes:
      - ./app:/app
      - gems:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:16.1-alpine
    container_name: postgres_rails
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - 5432:5432

volumes:
  postgres_data:
  gems:
