default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
    
development:
  <<: *default
  database: bibliotheca_development

test:
  <<: *default
  database: bibliotheca_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  